# Generated by Django 3.2.10 on 2021-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getfoxuser',
            name='ig_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='getfoxuser',
            name='ig_username',
            field=models.CharField(max_length=256),
        ),
    ]
