# Generated by Django 3.2.10 on 2021-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211221_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getfoxuser',
            name='ig_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='getfoxuser',
            name='ig_username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
