# Generated by Django 3.2.10 on 2021-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getfoxuser',
            name='ig_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
